package pl.exam.app.exceptions;

public class UserExamAlreadyExistsException extends RuntimeException
{
}
